const lessonTitle = "落花生";

const lessonData = [
    // ===== 第1段 =====
    ["我们", "wǒ men", "We", "Kami"],
    ["屋后", "wū hòu", "behind the house", "belakang rumah"],
    ["有", "yǒu", "there was", "ada"],
    ["半亩", "bàn mǔ", "half a mu", "setengah ekar"],
    ["隙地", "xì dì", "open space", "tanah kosong"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["让它", "ràng tā", "Let it", "Biarkan ia"],
    ["荒芜着", "huāng wú zhe", "lie waste", "terbiar"],
    ["怪可惜", "guài kě xī", "such a pity", "sayang"],
    ["，", "", "", ""],
    ["既然", "jì rán", "since", "memandangkan"],
    ["你们", "nǐ men", "you all", "kamu semua"],
    ["那么", "nà me", "so", "begitu"],
    ["爱吃花生", "ài chī huā shēng", "like eating peanuts", "suka makan kacang tanah"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "maka"],
    ["辟做", "pì zuò", "turn into", "jadikan"],
    ["花生园", "huā shēng yuán", "peanut garden", "kebun kacang tanah"],
    ["罢", "ba", "then", "lah"],
    ["。”", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["几姐弟", "jǐ jiě dì", "several siblings", "beberapa adik-beradik"],
    ["和", "hé", "and", "dan"],
    ["小丫头", "xiǎo yā tou", "young maid", "pembantu rumah"],
    ["都", "dōu", "all", "semua"],
    ["很", "hěn", "very", "sangat"],
    ["喜欢", "xǐ huān", "liked", "suka"],
    ["，", "", "", ""],
    ["──", "", "", ""],
    ["买种", "mǎi zhǒng", "buying seeds", "membeli benih"],
    ["的", "de", "", ""],
    ["买种", "mǎi zhǒng", "buy seeds", "membeli benih"],
    ["，", "", "", ""],
    ["动土", "dòng tǔ", "digging soil", "menggali tanah"],
    ["的", "de", "", ""],
    ["动土", "dòng tǔ", "dig soil", "menggali tanah"],
    ["，", "", "", ""],
    ["灌园", "guàn yuán", "watering the garden", "menyiram kebun"],
    ["的", "de", "", ""],
    ["灌园", "guàn yuán", "water the garden", "menyiram kebun"],
    ["；", "", "", ""],
    ["过不了", "guò bù liǎo", "within no more than", "tidak sampai"],
    ["几个月", "jǐ gè yuè", "a few months", "beberapa bulan"],
    ["，", "", "", ""],
    ["居然", "jū rán", "unexpectedly", "rupanya"],
    ["收获了", "shōu huò le", "harvested", "menuai"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["妈妈", "mā ma", "Mother", "Ibu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["今晚", "jīn wǎn", "Tonight", "Malam ini"],
    ["我们", "wǒ men", "we", "kita"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["做", "zuò", "hold", "mengadakan"],
    ["一个", "yí gè", "a", "sebuah"],
    ["收获节", "shōu huò jié", "harvest festival", "perayaan menuai"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["请", "qǐng", "invite", "jemput"],
    ["你们", "nǐ men", "your", "kamu punya"],
    ["爹爹", "diē die", "father", "ayah"],
    ["来", "lái", "to come", "datang"],
    ["尝尝", "cháng cháng", "taste", "merasa"],
    ["我们", "wǒ men", "our", "kami punya"],
    ["的", "de", "", ""],
    ["新花生", "xīn huā shēng", "new peanuts", "kacang tanah baru"],
    ["，", "", "", ""],
    ["如何", "rú hé", "what do you think", "bagaimana"],
    ["？”", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["都", "dōu", "all", "semua"],
    ["答应了", "dā yìng le", "agreed", "bersetuju"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["把花生", "bǎ huā shēng", "made the peanuts", "membuat kacang tanah"],
    ["做成", "zuò chéng", "into", "menjadi"],
    ["好几样", "hǎo jǐ yàng", "several kinds of", "beberapa jenis"],
    ["的", "de", "", ""],
    ["食品", "shí pǐn", "food", "makanan"],
    ["，", "", "", ""],
    ["还", "hái", "and", "dan"],
    ["吩附", "fēn fù", "instructed", "memberitahu"],
    ["这节期", "zhè jié qī", "this festival", "perayaan ini"],
    ["要", "yào", "should", "hendak"],
    ["在", "zài", "at", "di"],
    ["园里", "yuán lǐ", "in the garden", "dalam kebun"],
    ["的", "de", "", ""],
    ["茅亭", "máo tíng", "thatched pavilion", "pavilion beratap rumbia"],
    ["举行", "jǔ xíng", "hold", "diadakan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["那晚上", "nà wǎn shàng", "That night", "Malam itu"],
    ["的", "de", "", ""],
    ["天色", "tiān sè", "sky", "langit"],
    ["不大好", "bù dà hǎo", "not very good", "tidak begitu baik"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["爹爹", "diē die", "father", "ayah"],
    ["也", "yě", "also", "juga"],
    ["到来", "dào lái", "came", "datang"],
    ["，", "", "", ""],
    ["实在", "shí zài", "truly", "sungguh"],
    ["很难得", "hěn nán dé", "very rare", "sangat jarang"],
    ["！", "", "", ""],
    ["爹爹", "diē die", "Father", "Ayah"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你们", "nǐ men", "You all", "Kamu semua"],
    ["爱吃花生么", "ài chī huā shēng me", "like eating peanuts", "suka makan kacang tanah"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["我们", "wǒ men", "We", "Kami"],
    ["都", "dōu", "all", "semua"],
    ["争着", "zhēng zhe", "vied to", "berlumba-lumba"],
    ["答应", "dā yìng", "answer", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["爱", "ài", "Yes", "Suka"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["“", "", "", ""],
    ["谁能", "shuí néng", "Who can", "Siapa boleh"],
    ["把花生", "bǎ huā shēng", "tell the", "menyebut"],
    ["的", "de", "", ""],
    ["好处", "hǎo chù", "good points", "kebaikan"],
    ["说出来", "shuō chū lái", "good points of peanuts", "kebaikan kacang tanah"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["姐姐", "jiě jie", "Elder sister", "Kakak"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["花生", "huā shēng", "Peanuts", "Kacang tanah"],
    ["的", "de", "", ""],
    ["气味", "qì wèi", "smell", "bau"],
    ["很美", "hěn měi", "very nice", "sangat harum"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["哥哥", "gē ge", "Elder brother", "Abang"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["花生", "huā shēng", "Peanuts", "Kacang tanah"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["制油", "zhì yóu", "make oil", "menghasilkan minyak"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["我", "wǒ", "I", "Saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["无论", "wú lùn", "No matter", "Tidak kira"],
    ["何等", "hé děng", "what kind of", "apa-apa jenis"],
    ["人", "rén", "people", "orang"],
    ["都", "dōu", "can", "boleh"],
    ["可以", "kě yǐ", "", ""],
    ["用贱价", "yòng jiàn jià", "at a cheap price", "dengan harga murah"],
    ["买它来吃", "mǎi tā lái chī", "buy it to eat", "membelinya untuk dimakan"],
    ["；", "", "", ""],
    ["都", "dōu", "all", "semua"],
    ["喜欢吃它", "xǐ huān chī tā", "like to eat it", "suka memakannya"],
    ["。", "", "", ""],
    ["这就是", "zhè jiù shì", "This is", "Inilah"],
    ["它", "tā", "its", "ia punya"],
    ["的", "de", "", ""],
    ["好处", "hǎo chù", "good point", "kebaikan"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["爹爹", "diē die", "Father", "Ayah"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["花生", "huā shēng", "Peanuts", "Kacang tanah"],
    ["的", "de", "", ""],
    ["用处", "yòng chù", "uses", "kegunaan"],
    ["固然", "gù rán", "certainly", "memang"],
    ["很多", "hěn duō", "many", "banyak"],
    ["，", "", "", ""],
    ["但有一样", "dàn yǒu yí yàng", "but there is one thing", "tetapi ada satu perkara"],
    ["是很可贵的", "shì hěn kě guì de", "that is very valuable", "yang sangat bernilai"],
    ["。", "", "", ""],
    ["这小小的豆", "zhè xiǎo xiǎo de dòu", "This little bean", "Kacang kecil ini"],
    ["不像", "bù xiàng", "unlike", "tidak seperti"],
    ["那好看的", "nà hǎo kàn de", "those beautiful", "yang cantik"],
    ["苹果", "píng guǒ", "apples", "epal"],
    ["、", "", "", ""],
    ["桃子", "táo zi", "peaches", "buah persik"],
    ["、", "", "", ""],
    ["石榴", "shí liu", "pomegranates", "buah delima"],
    ["，", "", "", ""],
    ["把它们", "bǎ tā men", "hang their", "menggantung"],
    ["的果实", "de guǒ shí", "fruits", "buah-buahan"],
    ["悬在", "xuán zài", "on", "di"],
    ["枝上", "zhī shàng", "branches", "dahan"],
    ["，", "", "", ""],
    ["鲜红嫩绿", "xiān hóng nèn lǜ", "bright red and tender green", "merah segar hijau muda"],
    ["的颜色", "de yán sè", "color", "warna"],
    ["，", "", "", ""],
    ["令人", "lìng rén", "make people", "membuatkan orang"],
    ["一望", "yí wàng", "at a glance", "sekali pandang"],
    ["而发生", "ér fā shēng", "feel", "timbul"],
    ["羡慕", "xiàn mù", "envious", "iri hati"],
    ["的", "de", "", ""],
    ["心", "xīn", "feeling", "perasaan"],
    ["；", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["只把", "zhǐ bǎ", "only", "hanya"],
    ["果子", "guǒ zi", "fruit", "buah"],
    ["埋在", "mái zài", "buries in", "terkubur dalam"],
    ["地底", "dì dǐ", "the ground", "tanah"],
    ["，", "", "", ""],
    ["等到", "děng dào", "until", "sehingga"],
    ["成熟", "chéng shú", "ripe", "masak"],
    ["，", "", "", ""],
    ["才容人", "cái róng rén", "then allow people", "baru membenarkan orang"],
    ["把它挖出来", "bǎ tā wā chū lái", "to dig it out", "menggalinya"],
    ["。", "", "", ""],
    ["你们", "nǐ men", "You", "Kamu"],
    ["偶然", "ǒu rán", "occasionally", "kadang-kadang"],
    ["看见", "kàn jiàn", "see", "melihat"],
    ["一棵花生", "yì kē huā shēng", "a peanut plant", "sebatang pokok kacang tanah"],
    ["瑟缩地", "sè suō de", "shrinkingly", "terkulai"],
    ["长在地上", "zhǎng zài dì shàng", "growing on the ground", "tumbuh di tanah"],
    ["，", "", "", ""],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["立刻", "lì kè", "immediately", "segera"],
    ["辨出", "biàn chū", "tell", "membezakan"],
    ["它有没有", "tā yǒu méi yǒu", "whether it has", "ada atau tiada"],
    ["果实", "guǒ shí", "fruit", "buah"],
    ["，", "", "", ""],
    ["非得", "fēi děi", "must", "mesti"],
    ["等到", "děng dào", "wait until", "sehingga"],
    ["你", "nǐ", "you", "awak"],
    ["接触它", "jiē chù tā", "touch it", "menyentuhnya"],
    ["才能", "cái néng", "then can", "baru boleh"],
    ["知道", "zhī dào", "know", "tahu"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["我们", "wǒ men", "We", "Kami"],
    ["都", "dōu", "all", "semua"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["是的", "shì de", "Yes", "Ya"],
    ["。”", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["也", "yě", "also", "juga"],
    ["点点头", "diǎn diǎn tóu", "nodded", "mengangguk"],
    ["。", "", "", ""],
    ["爹爹", "diē die", "Father", "Ayah"],
    ["接下去说", "jiē xià qù shuō", "continued", "menyambung"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["所以", "suǒ yǐ", "So", "Maka"],
    ["你们", "nǐ men", "you", "kamu"],
    ["要", "yào", "should", "hendak"],
    ["像花生", "xiàng huā shēng", "be like peanuts", "seperti kacang tanah"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["它", "tā", "it", "ia"],
    ["是", "shì", "is", "ialah"],
    ["有用的", "yǒu yòng de", "useful", "berguna"],
    ["，", "", "", ""],
    ["不是", "bú shì", "not", "bukan"],
    ["伟大", "wěi dà", "great", "hebat"],
    ["、", "", "", ""],
    ["好看的", "hǎo kàn de", "good-looking", "cantik"],
    ["东西", "dōng xi", "things", "benda"],
    ["。”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那么", "nà me", "Then", "Maka"],
    ["人", "rén", "people", "manusia"],
    ["要", "yào", "should", "hendak"],
    ["做", "zuò", "be", "menjadi"],
    ["有用的", "yǒu yòng de", "useful", "berguna"],
    ["人", "rén", "people", "manusia"],
    ["，", "", "", ""],
    ["不要", "bú yào", "not", "jangan"],
    ["做", "zuò", "be", "menjadi"],
    ["伟大", "wěi dà", "great", "hebat"],
    ["、", "", "", ""],
    ["体面", "tǐ miàn", "showy", "bermuka"],
    ["的", "de", "", ""],
    ["人了", "rén le", "people", "manusia"],
    ["。”", "", "", ""],
    ["爹爹", "diē die", "Father", "Ayah"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这是", "zhè shì", "This is", "Inilah"],
    ["我", "wǒ", "my", "saya punya"],
    ["对于", "duì yú", "for", "terhadap"],
    ["你们", "nǐ men", "you", "kamu semua"],
    ["的", "de", "", ""],
    ["希望", "xī wàng", "hope", "harapan"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["我们", "wǒ men", "We", "Kami"],
    ["谈到", "tán dào", "talked until", "berbincang sehingga"],
    ["夜阑", "yè lán", "late at night", "lewat malam"],
    ["才散", "cái sàn", "dispersed", "baru bersurai"],
    ["，", "", "", ""],
    ["所有", "suǒ yǒu", "All", "Semua"],
    ["花生食品", "huā shēng shí pǐn", "peanut foods", "makanan kacang tanah"],
    ["虽然", "suī rán", "although", "walaupun"],
    ["没有了", "méi yǒu le", "were gone", "telah habis"],
    ["，", "", "", ""],
    ["然而", "rán ér", "however", "namun"],
    ["父亲", "fù qīn", "Father's", "Ayah punya"],
    ["的话", "de huà", "words", "kata-kata"],
    ["现在还", "xiàn zài hái", "still now", "sekarang masih"],
    ["印在", "yìn zài", "engraved on", "tercetak dalam"],
    ["我", "wǒ", "my", "saya punya"],
    ["心版上", "xīn bǎn shàng", "my heart", "hati"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["许地山", "xǔ dì shān", "Xu Dishan", "Xu Dishan"],
    ["《", "", "", ""],
    ["落花生", "luò huā shēng", "The Peanut", "Kacang Tanah"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
